'use strict';
(()=>{
 const $=id=>document.getElementById(id);let tracks=[],uploading=false;const players={music:$('stadiumPlayer'),effect:$('effectPlayer')},sources={music:null,effect:null};
 function message(text){$('soundStatus').textContent=text;}
 function stop(kind){players[kind].pause();players[kind].currentTime=0;if(sources[kind]){URL.revokeObjectURL(sources[kind]);sources[kind]=null;}players[kind].removeAttribute('src');players[kind].load();$(kind+'Now').textContent='Nothing playing';}
 function play(track){stop(track.kind);const a=players[track.kind];sources[track.kind]=URL.createObjectURL(track.blob);a.src=sources[track.kind];a.volume=Number($(track.kind+'Volume').value)/100;a.loop=track.kind==='music'&&$('loopMusic').checked;$(track.kind+'Now').textContent=track.name;const p=a.play();if(p)p.catch(()=>message('Could not play '+track.name+'. Try an MP3 or PCM WAV recording.'));}
 function render(){for(const kind of ['music','effect']){const list=$(kind+'List');list.replaceChildren();const items=tracks.filter(t=>t.kind===kind);if(!items.length){const empty=document.createElement('p');empty.className='help';empty.textContent=kind==='music'?'Upload music for stadium playback and player walk-ups.':'Upload effects such as applause, a horn, or an organ cue.';list.append(empty);}for(const t of items){const tile=document.createElement('div');tile.className='sound-tile';const name=document.createElement('strong');name.textContent=t.name;const bar=document.createElement('div');bar.className='toolbar';const start=document.createElement('button');start.textContent=kind==='effect'?'Play effect':'Play music';start.onclick=()=>play(t);const stopButton=document.createElement('button');stopButton.textContent='Stop';stopButton.onclick=()=>stop(kind);const remove=document.createElement('button');remove.className='delete-track';remove.textContent='Remove';remove.onclick=async()=>{if(!confirm('Remove '+t.name+' from this browser? Player assignments to this file will need to be cleared or replaced.'))return;try{stop(kind);await StadiumMedia.remove(t.id);await refresh();message('Removed '+t.name+' from this browser. Your original file is unchanged.');}catch(e){message(e.message);}};bar.append(start,stopButton,remove);tile.append(name,bar);list.append(tile);}}}
 async function refresh(){try{tracks=await StadiumMedia.list();render();}catch(e){message('Audio storage unavailable: '+e.message);}}
 for(const kind of ['music','effect']){$(kind+'Upload').onchange=async e=>{if(uploading)return;const files=[...e.target.files];if(!files.length)return;uploading=true;$('musicUpload').disabled=true;$('effectUpload').disabled=true;let count=0,errors=[];for(const f of files){try{await StadiumMedia.add(f,kind);count++;}catch(error){errors.push(error.message);}}e.target.value='';uploading=false;$('musicUpload').disabled=false;$('effectUpload').disabled=false;await refresh();message(count+' file(s) saved in this browser.'+(errors.length?' '+errors.join(' '):''));};$(kind+'Volume').oninput=()=>{players[kind].volume=Number($(kind+'Volume').value)/100;};players[kind].addEventListener('error',()=>message('This audio could not play. Check the file format.'));players[kind].addEventListener('ended',()=>$(kind+'Now').textContent='Finished');}
 $('loopMusic').onchange=()=>players.music.loop=$('loopMusic').checked;$('stopAllSounds').onclick=()=>{stop('music');stop('effect');message('All soundboard audio stopped.');};window.addEventListener('pagehide',()=>{stop('music');stop('effect');});refresh();
})();
