'use strict';
(()=>{
 let tracks=[],libraryError='',drag=null;
 const originalRender=render;
 function movePlayer(id,targetId,after=false){if(busy||id===targetId)return;const player=state.players.find(p=>p.id===id);const rest=state.players.filter(p=>p.id!==id),at=rest.findIndex(p=>p.id===targetId);if(!player||at<0)return;rest.splice(at+(after?1:0),0,player);state.players=rest;save();render();$('reorderStatus').textContent=player.name+' moved to roster slot '+(rest.indexOf(player)+1)+'.';}
 // Expose one narrow helper for keyboard ordering and automated interaction checks.
 window.StadiumRoster={movePlayer};
 function resetMarkers(){for(const row of $('roster').children)row.classList.remove('drop-before','drop-after');}
 function targetAt(y){const rows=[...$('roster').children].filter(r=>Number(r.dataset.playerId)!==drag.id);if(!rows.length)return;let row=rows.find(r=>{const box=r.getBoundingClientRect();return y<box.top+box.height/2;});const after=!row;if(!row)row=rows[rows.length-1];drag.target=Number(row.dataset.playerId);drag.after=after;resetMarkers();row.classList.add(after?'drop-after':'drop-before');}
 function scrollHost(handle){for(let e=handle.parentElement;e;e=e.parentElement){const css=getComputedStyle(e);if(/auto|scroll/.test(css.overflowY)&&e.scrollHeight>e.clientHeight+2)return e;}return document.scrollingElement;}
 function animateDrag(){if(!drag?.active)return;const host=drag.host,root=host===document.scrollingElement,rect=root?{top:0,bottom:innerHeight}:host.getBoundingClientRect();let speed=0;if(drag.y<rect.top+65)speed=-Math.min(20,(rect.top+65-drag.y)/3);else if(drag.y>rect.bottom-65)speed=Math.min(20,(drag.y-rect.bottom+65)/3);if(speed){host.scrollTop+=speed;targetAt(drag.y);}drag.frame=requestAnimationFrame(animateDrag);}
 function endDrag(commit){if(!drag)return;const d=drag;drag=null;cancelAnimationFrame(d.frame);d.row.classList.remove('drag-source');d.ghost?.remove();resetMarkers();document.body.classList.remove('dragging-roster');try{d.handle.releasePointerCapture(d.pointer);}catch(e){}if(commit&&d.active&&d.target!==undefined)movePlayer(d.id,d.target,d.after);}
 function bindHandle(handle,row,p){handle.onpointerdown=e=>{if(busy||drag||e.button!==0)return;e.preventDefault();drag={id:p.id,row,handle,pointer:e.pointerId,startX:e.clientX,startY:e.clientY,x:e.clientX,y:e.clientY,host:scrollHost(handle),active:false};handle.setPointerCapture(e.pointerId);};
 handle.onpointermove=e=>{if(!drag||drag.pointer!==e.pointerId)return;drag.x=e.clientX;drag.y=e.clientY;if(!drag.active&&Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>6){drag.active=true;drag.ghost=document.createElement('div');drag.ghost.className='drag-ghost';drag.ghost.textContent=p.name;document.body.append(drag.ghost);row.classList.add('drag-source');document.body.classList.add('dragging-roster');animateDrag();}if(drag.active){drag.ghost.style.left=Math.min(e.clientX+12,innerWidth-200)+'px';drag.ghost.style.top=(e.clientY+12)+'px';targetAt(e.clientY);}};
 handle.onpointerup=()=>endDrag(true);handle.onpointercancel=()=>endDrag(false);handle.onlostpointercapture=()=>endDrag(false);
 handle.onkeydown=e=>{if(busy)return;const i=state.players.findIndex(x=>x.id===p.id);if(!['ArrowUp','ArrowDown','Home','End'].includes(e.key))return;e.preventDefault();const at=e.key==='Home'?0:e.key==='End'?state.players.length-1:Math.max(0,Math.min(state.players.length-1,i+(e.key==='ArrowUp'?-1:1)));movePlayer(p.id,state.players[at].id,at>i);$('roster').querySelector('[data-player-id="'+p.id+'"] .drag-handle')?.focus();};
 }
 function decorate(){for(const [i,row]of [...$('roster').children].entries()){const p=state.players[i];row.dataset.playerId=p.id;const order=row.children[4],handle=document.createElement('button');handle.type='button';handle.className='drag-handle';handle.textContent='⠿';handle.disabled=busy;handle.setAttribute('aria-label','Drag '+p.name+' to reorder. Keyboard: arrows, Home or End.');handle.title='Drag to any position. Keyboard: arrows, Home / End.';order.prepend(handle);bindHandle(handle,row,p);
 const cell=document.createElement('td');cell.className='walkup-cell';const label=document.createElement('label');label.textContent='Walk-up music';const select=document.createElement('select');select.setAttribute('aria-label','Walk-up music for '+p.name);label.htmlFor='music-'+p.id;select.id='music-'+p.id;const none=document.createElement('option');none.value='';none.textContent='No music';select.append(none);for(const t of tracks.filter(t=>t.kind==='music')){const option=document.createElement('option');option.value=t.id;option.textContent=t.name;select.append(option);}if(p.musicId&&!tracks.some(t=>t.id===p.musicId)){const missing=document.createElement('option');missing.value=p.musicId;missing.textContent='Assigned file unavailable';select.append(missing);}select.value=p.musicId||'';select.disabled=busy;select.onchange=()=>{p.musicId=select.value;save();render();};cell.append(label,select);row.append(cell);
 }$('walkupEnabled').checked=state.walkupEnabled;$('walkupEnabled').disabled=busy;$('walkupVolume').value=String(Math.round(state.walkupVolume*100));$('walkupVolume').disabled=busy;$('walkupLevel').textContent=Math.round(state.walkupVolume*100)+'%';$('musicLibraryStatus').textContent=libraryError||tracks.filter(t=>t.kind==='music').length+' music tracks on this browser. Add tracks in Soundboard.';}
 render=function(){originalRender();decorate();};
 $('walkupEnabled').onchange=()=>{state.walkupEnabled=$('walkupEnabled').checked;save();render();};$('walkupVolume').oninput=()=>{$('walkupLevel').textContent=$('walkupVolume').value+'%';};$('walkupVolume').onchange=()=>{state.walkupVolume=Number($('walkupVolume').value)/100;save();render();};
 document.addEventListener('keydown',e=>{if(e.key==='Escape')endDrag(false);});
 async function refreshTracks(){try{tracks=await StadiumMedia.list();libraryError='';}catch(e){libraryError='Audio storage unavailable: '+e.message;}if(!drag)render();}
 window.addEventListener('storage',e=>{if(e.key==='stadium.audio.revision')refreshTracks();});render();refreshTracks();
})();
